description: The hackathon from beyond the wall is back for a virtual hackathon!

links:
    interest:  https://www.youtube.com/watch?v=6n3pFFPSlW4
    volunteer: https://www.youtube.com/watch?v=q6EoRBvdVPQ

